import React, { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { CURRENT_QUEUE } from '../../../data/mockData';
import { kioskSound } from '../../../lib/kioskSound';
import type { KioskScreenProps } from '../KioskLayout';
import { useIsPortrait } from '../../../context/KioskOrientationContext';
import { useCMS } from '../../../context/CMSContext';

const PINK = '#E91E8C';
const ROSE = '#FF6BB5';
const AQUA = '#06B6D4';
const DARK = '#0D1421';
const FONT = "'Nunito Sans', 'Plus Jakarta Sans', sans-serif";

// 2.5D claymorphism tooth doctor mascot — generated by Stitch
const MASCOT_SRC =
  'https://lh3.googleusercontent.com/aida/AP1WRLsY5SYPxo1NL0ndRpHMap9j0mmpZiHfP9VPTmyEPNM9MJfRunzmihmzdfXaw_aLPYaMB0kJsTkpqVcwe74XbkI4lAN-SLFYWcVA0G0gUgXqH_xFs1Sy5CGLwYn2xkJkqkETu_J9eC2aLjwNW61RwiJkqD_MrCwa0QpoV-O6TTsw9_xY-DoIjTPXMPTWN7oxpexIoVal-IsLIM-4AihCR30B4YcPMk4wN-qnkxf66GSy60bHNiSxkvSvcx-l';

function LiveClock() {
  const [time, setTime] = useState(new Date());
  useEffect(() => {
    const id = setInterval(() => setTime(new Date()), 1000);
    return () => clearInterval(id);
  }, []);
  return (
    <div>
      <div style={{
        fontSize: 72, fontWeight: 800, color: PINK, lineHeight: 1,
        fontVariantNumeric: 'tabular-nums', letterSpacing: -3, fontFamily: FONT,
      }}>
        {time.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}
      </div>
      <div style={{ fontSize: 15, color: '#9CA3AF', fontWeight: 600, marginTop: 6, fontFamily: FONT }}>
        {time.toLocaleDateString('id-ID', { weekday: 'long', day: 'numeric', month: 'long' })}
      </div>
    </div>
  );
}

export function KioskWelcome({ goTo, setState }: KioskScreenProps) {
  const portrait = useIsPortrait();
  const { cms } = useCMS();
  const bookingCodeCheckin = cms.kioskSettings?.bookingCodeCheckin ?? true;
  const [lang, setLang] = useState<'id' | 'en'>('id');

  const handleCheckin = () => {
    kioskSound('tap');
    setState(prev => ({ ...prev, language: lang }));
    goTo('language');
  };

  const handleQueue = (e: React.MouseEvent) => {
    e.stopPropagation();
    kioskSound('select');
    goTo('queue-display');
  };

  const handleOmdc = (e: React.MouseEvent) => {
    e.stopPropagation();
    kioskSound('select');
    setState(prev => ({ ...prev, language: lang }));
    goTo('omdc-recall');
  };

  const LABEL = {
    id: {
      title: 'Selamat Datang!',
      sub: 'Klinik Gigi Keluarga Terpercaya',
      checkin: 'MULAI CHECK-IN',
      scanOmdc: 'KODE BOOKING / SCAN',
      hint: 'Ketuk tombol untuk memulai',
      nowServing: 'Now Serving',
      checkQueue: 'Cek Antrian',
      services: '8 Layanan',
    },
    en: {
      title: 'Welcome!',
      sub: 'Your Trusted Family Dental Clinic',
      checkin: 'START CHECK-IN',
      scanOmdc: 'BOOKING CODE / SCAN',
      hint: 'Tap a button to start',
      nowServing: 'Now Serving',
      checkQueue: 'Check Queue',
      services: '8 Services',
    },
  }[lang];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.4 }}
      style={{
        width: '100%', height: '100%',
        position: 'relative', overflow: 'hidden',
        background: '#FFF5F9', fontFamily: FONT,
      }}
    >
      {/* 4px brand strip */}
      <div style={{
        position: 'absolute', top: 0, left: 0, right: 0, height: 4,
        background: `linear-gradient(90deg, ${PINK}, ${ROSE}, ${AQUA})`, zIndex: 30,
      }} />

      {/* Ambient blur blobs */}
      <div style={{ position: 'absolute', top: 80, left: '10%', width: 256, height: 256, borderRadius: '50%', background: 'rgba(223,14,132,0.07)', filter: 'blur(60px)', pointerEvents: 'none', zIndex: 0 }} />
      <div style={{ position: 'absolute', bottom: 80, right: '20%', width: 384, height: 384, borderRadius: '50%', background: 'rgba(0,101,119,0.06)', filter: 'blur(60px)', pointerEvents: 'none', zIndex: 0 }} />
      <div style={{ position: 'absolute', top: '40%', left: '50%', width: 192, height: 192, borderRadius: '50%', background: 'rgba(252,105,179,0.06)', filter: 'blur(40px)', pointerEvents: 'none', zIndex: 0 }} />

      {/* Layout */}
      <div style={{
        position: 'absolute', inset: 0,
        display: 'flex', flexDirection: portrait ? 'column' : 'row',
        padding: portrait ? '24px 20px 20px' : '20px 28px 20px 32px',
        gap: 20, zIndex: 1,
      }}>

        {/* ── LEFT PANEL ── */}
        <motion.div
          initial={{ x: -30, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ duration: 0.55, ease: [0.22, 1, 0.36, 1] }}
          style={{
            width: portrait ? '100%' : '44%',
            height: portrait ? '38%' : 'auto',
            display: 'flex', flexDirection: 'column',
            justifyContent: 'space-between',
          }}
        >
          {/* Brand badge */}
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 12, alignSelf: 'flex-start',
            background: 'white', borderRadius: 9999,
            padding: '12px 24px 12px 16px',
            border: '1px solid rgba(220,226,245,0.8)',
            boxShadow: '0 4px 12px rgba(233,30,140,0.08), inset 0 1px 0 rgba(255,255,255,0.9)',
          }}>
            <svg width={28} height={28} viewBox="0 0 100 115" fill="none">
              <path d="M50 8C35 8 23 20 23 35c0 9 3 16 7 24 4 8 6.5 16 6.5 27 0 3 2 5 4.5 5h18c2.5 0 4.5-2 4.5-5 0-11 2.5-19 6.5-27 4-8 7-15 7-24C77 20 65 8 50 8z" fill={PINK} />
              <path d="M43 54l5 5 9-11" stroke="white" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            <span style={{ fontSize: 20, fontWeight: 900, color: DARK, letterSpacing: -0.5, fontFamily: FONT }}>
              OMDC DENTAL
            </span>
          </div>

          {/* Stitch mascot illustration */}
          {!portrait && (
            <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' }}>
              <motion.img
                src={MASCOT_SRC}
                alt="OMDC Dental mascot doctor"
                animate={{ y: [0, -15, 0] }}
                transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut' }}
                style={{
                  width: '80%', maxWidth: 400,
                  objectFit: 'contain',
                  filter: 'drop-shadow(0 24px 48px rgba(0,0,0,0.15))',
                  position: 'relative', zIndex: 1,
                }}
              />
              <motion.span
                animate={{ opacity: [0.5, 1, 0.5], scale: [0.9, 1.1, 0.9] }}
                transition={{ duration: 2.5, repeat: Infinity }}
                style={{ position: 'absolute', top: '20%', right: '12%', fontSize: 28, color: PINK, pointerEvents: 'none' }}
              >✦</motion.span>
              <motion.span
                animate={{ opacity: [0.3, 0.8, 0.3], scale: [0.9, 1.1, 0.9] }}
                transition={{ duration: 2.5, repeat: Infinity, delay: 1 }}
                style={{ position: 'absolute', bottom: '28%', left: '8%', fontSize: 20, color: AQUA, pointerEvents: 'none' }}
              >✦</motion.span>
            </div>
          )}

          {/* Stat pills — 2-in-row + 1-with-lang-toggle */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10, width: '100%' }}>
            <div style={{ display: 'flex', gap: 10 }}>
              {[
                { icon: '👥', label: '10.000+ Pasien Puas', border: 'rgba(233,30,140,0.22)' },
                { icon: '🦷', label: '8 Dokter Spesialis', border: 'rgba(255,107,181,0.22)' },
              ].map(s => (
                <div key={s.label} style={{
                  flex: 1, background: 'white', borderRadius: 16,
                  padding: '12px 14px', display: 'flex', alignItems: 'center', gap: 10,
                  border: `2px solid ${s.border}`,
                  boxShadow: '4px 4px 10px rgba(233,30,140,0.06), -4px -4px 10px rgba(255,255,255,0.9), inset 1px 1px 2px rgba(255,255,255,0.8)',
                }}>
                  <span style={{ fontSize: 20 }}>{s.icon}</span>
                  <span style={{ fontSize: 13, fontWeight: 600, color: '#594048', fontFamily: FONT, lineHeight: 1.3 }}>{s.label}</span>
                </div>
              ))}
            </div>
            <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
              <div style={{
                flex: 1, background: 'white', borderRadius: 16,
                padding: '12px 14px', display: 'flex', alignItems: 'center', gap: 10,
                border: '2px solid rgba(6,182,212,0.22)',
                boxShadow: '4px 4px 10px rgba(6,182,212,0.06), -4px -4px 10px rgba(255,255,255,0.9), inset 1px 1px 2px rgba(255,255,255,0.8)',
              }}>
                <span style={{ fontSize: 20 }}>📅</span>
                <span style={{ fontSize: 13, fontWeight: 600, color: '#594048', fontFamily: FONT }}>Senin–Sabtu Buka</span>
              </div>
              {/* Language toggle */}
              <div style={{
                display: 'flex', background: 'white', borderRadius: 9999,
                padding: 4, border: '1px solid rgba(220,226,245,0.8)',
                boxShadow: '0 2px 8px rgba(0,0,0,0.06)', flexShrink: 0,
              }}>
                {(['id', 'en'] as const).map(l => (
                  <button
                    key={l}
                    onClick={e => { e.stopPropagation(); kioskSound('tap'); setLang(l); }}
                    style={{
                      padding: '9px 18px', borderRadius: 9999,
                      fontSize: 14, fontWeight: 800, fontFamily: FONT,
                      textTransform: 'uppercase', cursor: 'pointer', border: 'none',
                      background: lang === l ? PINK : 'transparent',
                      color: lang === l ? 'white' : PINK,
                      transition: 'all 0.18s',
                    }}
                  >
                    {l.toUpperCase()}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </motion.div>

        {/* ── RIGHT PANEL: Glassmorphism card (Stitch design) ── */}
        <motion.div
          initial={{ x: 30, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ duration: 0.55, delay: 0.08, ease: [0.22, 1, 0.36, 1] }}
          style={{
            flex: 1,
            display: 'flex', flexDirection: 'column',
            gap: portrait ? 14 : 18,
            padding: portrait ? '20px 24px 24px' : '40px 44px 32px',
            background: 'rgba(255,255,255,0.45)',
            backdropFilter: 'blur(24px)',
            WebkitBackdropFilter: 'blur(24px)',
            borderRadius: portrait ? 32 : 48,
            border: '1.5px solid rgba(255,255,255,0.65)',
            boxShadow: '0 20px 60px rgba(233,30,140,0.07), 0 8px 24px rgba(0,0,0,0.04)',
          }}
        >
          {/* Clock + queue chip */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <LiveClock />
            <div style={{
              background: 'white', borderRadius: 9999, padding: '10px 18px',
              display: 'flex', alignItems: 'center', gap: 10,
              boxShadow: '0 4px 12px rgba(233,30,140,0.08), inset 0 1px 0 rgba(255,255,255,0.9)',
              border: '1px solid rgba(220,226,245,0.8)',
            }}>
              <motion.span
                animate={{ opacity: [1, 0.3, 1] }}
                transition={{ duration: 1.5, repeat: Infinity }}
                style={{ width: 11, height: 11, borderRadius: '50%', background: PINK, display: 'block', boxShadow: `0 0 8px ${PINK}` }}
              />
              <span style={{ fontSize: 14, fontWeight: 700, color: DARK, fontFamily: FONT }}>
                {LABEL.nowServing}: {CURRENT_QUEUE}
              </span>
            </div>
          </div>

          {/* Welcome heading */}
          <div>
            <h1 style={{
              fontSize: portrait ? 48 : 72, fontWeight: 800, lineHeight: 1.0,
              color: DARK, fontFamily: FONT, letterSpacing: -2, margin: 0,
            }}>
              {LABEL.title}
            </h1>
            <p style={{ fontSize: portrait ? 16 : 22, color: '#9CA3AF', fontWeight: 600, marginTop: 8, margin: '8px 0 0' }}>
              {LABEL.sub}
            </p>
          </div>

          {/* CTA buttons */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12, flex: 1, justifyContent: 'center' }}>
            {/* Primary — MULAI CHECK-IN */}
            <motion.button
              whileTap={{ y: 4 }}
              onClick={handleCheckin}
              style={{
                width: '100%', height: portrait ? 88 : 120,
                display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 14,
                borderRadius: 32, border: 'none', cursor: 'pointer',
                background: `linear-gradient(135deg, #FF4DAD, ${PINK})`,
                color: 'white', fontFamily: FONT, fontWeight: 800,
                fontSize: portrait ? 22 : 28, letterSpacing: 0.5,
                boxShadow: '0 10px 20px -5px rgba(223,14,132,0.35), inset 0 -6px 0 #B30069, inset 0 1px 0 rgba(255,255,255,0.25)',
                position: 'relative', overflow: 'hidden',
              }}
            >
              <svg width={34} height={34} viewBox="0 0 24 24" fill="none">
                <path d="M12 22s-8-3-8-10V5l8-3 8 3v7c0 7-8 10-8 10z"
                  fill="rgba(255,255,255,0.25)" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M9 12l2 2 4-4" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              <span>{LABEL.checkin}</span>
            </motion.button>

            {bookingCodeCheckin && (
              <motion.button
                whileTap={{ y: 2 }}
                onClick={handleOmdc}
                style={{
                  width: '100%', height: portrait ? 70 : 88,
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 12,
                  borderRadius: 20, border: '3px solid rgba(6,182,212,0.28)', cursor: 'pointer',
                  background: 'rgba(255,255,255,0.85)',
                  color: AQUA, fontFamily: FONT, fontWeight: 700,
                  fontSize: portrait ? 18 : 22, letterSpacing: 0.3,
                  boxShadow: '0 10px 20px -5px rgba(0,101,119,0.15), inset 0 -4px 0 rgba(0,101,119,0.18)',
                }}
              >
                <svg width={26} height={26} viewBox="0 0 24 24" fill="none" stroke={AQUA} strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="3" y="3" width="5" height="5" rx="1" />
                  <rect x="16" y="3" width="5" height="5" rx="1" />
                  <rect x="3" y="16" width="5" height="5" rx="1" />
                  <path d="M16 16h5v5M16 16v5" />
                  <path d="M9 3v5M3 9h5M9 12v8M12 9h8M12 12h2" />
                </svg>
                <span>{LABEL.scanOmdc}</span>
              </motion.button>
            )}
          </div>

          {/* Feature tiles */}
          {!portrait && (
            <div style={{ display: 'flex', gap: 12 }}>
              {[
                { icon: '📋', label: LABEL.checkQueue, bg: '#f1f3ff', border: 'rgba(220,226,245,0.8)', action: handleQueue },
                { icon: '🦷', label: LABEL.services, bg: '#f1f3ff', border: 'rgba(220,226,245,0.8)', action: handleCheckin },
              ].map((item, i) => (
                <motion.button
                  key={i}
                  whileTap={{ scale: 0.97 }}
                  onClick={item.action}
                  style={{
                    flex: 1, background: item.bg,
                    border: `1px solid ${item.border}`,
                    borderRadius: 20, cursor: 'pointer',
                    padding: '18px 20px',
                    display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8,
                    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
                  }}
                >
                  <span style={{ fontSize: 26 }}>{item.icon}</span>
                  <span style={{ fontSize: 14, fontWeight: 700, color: DARK, fontFamily: FONT }}>{item.label}</span>
                </motion.button>
              ))}
            </div>
          )}

          {/* Animated hint */}
          <motion.div
            animate={{ opacity: [0.5, 1, 0.5] }}
            transition={{ duration: 2.2, repeat: Infinity, ease: 'easeInOut' }}
            style={{ textAlign: 'center' }}
          >
            <span style={{ fontSize: 14, fontWeight: 700, color: PINK, fontFamily: FONT }}>
              ● {LABEL.hint} ●
            </span>
          </motion.div>
        </motion.div>
      </div>
    </motion.div>
  );
}
